version: "3.8"
services:
  webapp:
    build: .
    ports:
      - 3636:8888
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=1
      - TZ=Asia/Jakarta
    volumes:
      - ./base.sql:/docker-entrypoint-initdb.d/base.sql